name: "Deploy Test"
on: ["push"]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Build Image docker
        id: build_docker
        env:
          USERNAME: ${{ secret.DOCKER_USERNAME }}
          PASS: ${{ secret.DOCKER_PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: $USERNAME
          password: $PASSWORD

      - name: "Build and Push"
        uses: docker/build-push-action@v5
        with:
          context: /backend
          push: true
          tags: |
            marcotfm/zoologico-ada:v1
            marcotfm/zoologico-ada:latest

