name: "Create Infraestructure GCP"

on:
  push:
    branches:
      - main

jobs:
   CI:
      runs-on: "ubuntu-latest"
      steps:
        - name: "Checkout"
          uses: "actions/checkout@v3"
          with:
            ref: main
        
        - name: "Login Registry Docker"
          uses: docker/login-action@3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: "Build Image"
          uses: docker/build-push-action@5
          with:
            push: true
            tags: |
              "${{ secrets.DOCKER_USERNAME}}:zoologico:v3"
              "${{ secrets.DOCKER_USERNAME}}:zoologico:latest"
            context: ./backend

  CD:
    runs-on: "ubuntu-latest"
    needs: CI
    steps:
      - name: Apply Infraestructure
          


              